apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bear-review
  template:
    metadata:
      labels:
        app: bear-review
    spec:
      containers:
        - name: app
          image: ghcr.io/org/bear-review:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bear-review
spec:
  selector:
    app: bear-review
  ports:
    - port: 80
      targetPort: 3000
