name: Backend CI
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          pip install -e python
          pip install pytest pytest-cov
      - name: Run PyTest
        run: pytest -q --cov=python --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-xml
          path: coverage.xml
